### PR TITLE
Changes to make type-module tolerant

### PR DESCRIPTION
**Pull request by michaelfig**
Implements standard-things/esm#877.

### CODE REVIEW

**Review by kriskowal — APPROVED** [review]
It might be good to have a test that illustrates the intended consequence. Are we going to publish an `@agoric/esm` fork? (I would like to reserve `@endo/esm` for the possibility of an Endo based `node -r @endo/esm` feature.

**Comment by shivjm** [comment]
Not sure what exactly is going on, but thank you for this. After pulling out my hair for hours over standard-things/esm#868, installing this branch with <kbd>npm i -D agoric-labs/esm#mfig-type-module-tolerant</kbd> was the only thing that got my code working.

**Comment by michaelfig** [comment]
> Not sure what exactly is going on, but thank you for this. After pulling out my hair for hours over [standard-things#868](https://github.com/standard-things/esm/issues/868), installing this branch with npm i -D agoric-labs/esm#mfig-type-module-tolerant was the only thing that got my code working.

Thanks @shivjm!  If you need to point anybody else at this branch, I've updated the [README](https://github.com/agoric-labs/esm#readme), and posted a reference to it at standard-things/esm#897.

**Comment by michaelfig** [comment]
Note to future self: don't delete this branch in case anybody still depends on it!

**Comment by shivjm** [comment]
Many thanks! Will you be carrying on development in the `Agoric` branch or in `Agoric-built`? For my part, at least, I can simply update my code to point to wherever you think makes sense.

**Comment by michaelfig** [comment]
> Many thanks! Will you be carrying on development in the `Agoric` branch or in `Agoric-built`? For my part, at least, I can simply update my code to point to wherever you think makes sense.

`Agoric` is the non-minified code.  `Agoric-built` is just the minified version.  We will keep `Agoric-built` up-to-date if we make any changes to `Agoric`, so it really is up to you which one you want to point to.

**Comment by shivjm** [comment]
Gotcha. I’ll update the branch I’m using. Thanks again!

**Pull request merged**
